#!/bin/bash
#
#

RETVAL=0

realpath="`ls -l $0 | awk -F '> ' '{print $2}'`"

if [ "" = "$realpath" ]; then
	SH_PATH=$(cd "$(dirname $0)"; pwd)
else
        SH_PATH=$(dirname $realpath)
fi

gateway=""
vpn_gateway=""

install() {
	sudo ln -sf "$SH_PATH/bfw" /usr/bin/bfw
	echo "breadGFW installed successful"
}

check_empty() {
        if [ "" = "$2" ]; then
                echo "$1 is empty"
                exit 1
        fi
}

parse_ip() {
	ip=$(echo "$1" | awk -F '/' '{print ($2+0)"."$1}' | awk -F '.' '{
		ip1=$2+0;
		ip2=$3+0;
		ip3=$4+0;
		ip4=$5+0;
		netmask=$1+0
		if(netmask==0){netmask=32}
		ip=ip1"."ip2"."ip3"."ip4"/"netmask;
		print ip
	}')

	if [ "0.0.0.0/32" = "$ip" ]; then
                echo "ip format error"
                exit 1
        else
                echo $ip
                exit 0
        fi
}

add_china_ip() {
	set_gateway
	if [ "" = "$gateway" ]; then
		echo "no available gateway"
		exit 1
	fi

	cat "$SH_PATH/china_ipv4.lst"  | while read ip
	do
		ip=$(parse_ip $ip)
        	/sbin/route add -net $ip -gateway $gateway
	done
}

delete_china_ip() {
        cat "$SH_PATH/china_ipv4.lst" | while read ip
        do
                ip=$(parse_ip $ip)
                delete_route $ip
        done
}

add_redirect_ip() {
	if [ -f "$SH_PATH/redirect_ip.lst" ]; then
        	set_gateway
		if [ "" = "$gateway" ]; then
                	echo "no available gateway"
                	exit 1
        	fi

        	cat "$SH_PATH/redirect_ip.lst"  | while read ip
        	do
                	ip=$(parse_ip $ip)
                	/sbin/route add -net $ip -gateway $gateway
        	done
	fi
}

delete_redirect_ip() {
	if [ -f "$SH_PATH/redirect_ip.lst" ]; then
        	cat "$SH_PATH/redirect_ip.lst" | while read ip
        	do
                	ip=$(parse_ip $ip)
                	delete_route $ip
        	done
	fi
}

set_gateway() {
	gateway=`netstat -nr | grep '^default.*UGSc.*en' | head -n 1 | awk '{print $2}'`
}

set_vpn_gateway() {
	vpn_gateway=`netstat -nr | grep '^default.*UGSc.*ppp' | head -n 1 | awk '{print $2}'`
}

add_route() {
	check_empty route $1
	set_gateway
	if [ "" = "$gateway" ]; then
                echo "no available gateway"
                exit 1
        fi
	/sbin/route add -net $1 -gateway $gateway
}

delete_route() {
	check_empty route $1
	/sbin/route delete -net $1
}

delete_line() {
	file=$1
	match=$2

	match=${match//\./\\.}
	match=${match//\//\\\/}

	sed -i '.bak' "/$match/d" $file
}

list_ip() {
        cat "$SH_PATH/redirect_ip.lst"
}

add_ip() {
	check_empty ip $1

	ip=$(parse_ip $1)
	if [ "0" = "$?" ]; then
		echo $ip >> "$SH_PATH/redirect_ip.lst"
		echo "add ip $ip"
		add_route $ip
	else
		echo $ip
		exit 1
	fi
}

delete_ip() {
	check_empty ip $1

        ip=$(parse_ip $1)
        if [ "0" = "$?" ]; then
                delete_line "$SH_PATH/redirect_ip.lst" "$ip"
		echo "delete ip $ip"
                delete_route $ip
        else
                echo $ip
                exit 1
        fi
}

list_site() {
        cat "$SH_PATH/redirect_site.lst"
}

add_site() {
	check_empty domain $1
	
	echo $1 >> "$SH_PATH/redirect_site.lst"
        echo "add domain $1"
	
	nslookup $1 | awk '/^Address.*[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/{print $2}' | while read ip
        do
                add_ip $ip
        done
}

delete_site() {
	check_empty domain $1

        delete_line "$SH_PATH/redirect_site.lst" "$1"
        echo "delete domain $1"
	
	nslookup $1 | awk '/^Address.*[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/{print $2}' | while read ip
        do
                delete_ip $ip
        done
}

add_nameserver_ip() {
        awk '/^nameserver/{print $2}' /etc/resolv.conf | while read ip
        do
		add_ip $ip
        done
}

delete_nameserver_ip() {
        awk '/^nameserver/{print $2}' /etc/resolv.conf | while read ip
        do
                delete_ip $ip
        done
}

connect_vpn() {
	if [ "" = "$1" ]; then
		vpn="breakGFW"
	else
		vpn=$1
	fi

	networksetup -connectpppoeservice $vpn
	
	start_time=0	
	
	echo "start connect vpn"

	while [ 0 ]; do
		end_time=$(date +%s)
		timeout=`expr $end_time - $start_time`
		if [ $timeout -gt 10 ]; then
        		networksetup -connectpppoeservice $vpn
			start_time=$(date +%s)
		fi

		set_vpn_gateway
		if [ "" = "$vpn_gateway" ]; then
			echo -n .
			sleep 1
		else
			echo ""
			echo "connect vpn successful"
            		break
		fi
	done
}

disconnect_vpn() {
        if [ "" = "$1" ]; then
                vpn="breakGFW"
        else
                vpn=$1
        fi
        
        networksetup -disconnectpppoeservice $vpn
	
	echo "disconnect vpn"
	
        delete_china_ip
        delete_redirect_ip
}


start() {
	while [ 0 ]; do
		if [ "0" != "`nslookup 8.8.8.8 | grep google-public-dns-a.google.com | wc -l`" ]; then
			
			add_china_ip
                        add_redirect_ip

			connect_vpn $1			
			
			add_nameserver_ip
			if [ "0" = "`nslookup 8.8.8.8 | grep google-public-dns-a.google.com | wc -l`" ]; then
				delete_nameserver_ip
			fi

			echo "Welcome to internet"

			break
		else
			echo -n .
			sleep 1
		fi
	done
}

stop() {
	disconnect_vpn $1
	echo "You are back to the GWF"
}

auto_start() {
        while [ 0 ]; do
                if [ "0" != "`nslookup 8.8.8.8 | grep google-public-dns-a.google.com | wc -l`" ]; then
                        connect_vpn $1

                        echo "Welcome to internet"

                        break
                else
                        echo -n .
                        sleep 1
                fi
        done
}

auto() {
	while [ 0 ]; do
		set_vpn_gateway
                if [ "" = "$vpn_gateway" ]; then
			auto_start $1
		else
			sleep 1
                fi
        done
}

case "$1" in
	list)
                case "$2" in
                        site)
				echo "redirect sites"
                                list_site
                                ;;
                        ip)
				echo "redirect ips"
				list_ip
                                ;;
                        *)
				echo "redirect ips and sites"
				list_ip
				list_site
                esac
                ;;
	add)
		case "$2" in
			site)
				add_site $3
				;;
			ip)
				if [ "" = "$3" ]; then
					add_china_ip
					add_redirect_ip
				else
					add_ip $3
				fi
				;;
			route)
				add_route $3
				;;
			*)
				echo $"Usage: $0 $1 {ip|route}"
		esac
		;;
	delete)
		case "$2" in
			site)
				delete_site $3
				;;
                        ip)
				if [ "" = "$3" ]; then
                                        delete_china_ip
                                        delete_redirect_ip
                                else
                                	delete_ip $3
				fi
                                ;;
                        route)
                                delete_route $3
                                ;;
                        *)
                                echo $"Usage: $0 $1 {ip|route}"
                esac
		;;
	start)
		start $2
		;;
	stop)
		stop $2
		;;
	restart)
		stop $2
		start $2
		;;
	auto)
		auto $2
		;;
	install)
		install
		;;
	*)
		echo $"Usage: $0 {install|start|stop|restart|auto|list|add|delete}"
		RETVAL=2
esac
exit $RETVAL
